config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end
  resources :todos
  post 'search', to: 'todos#search'
  delete 'destroy_selected', to: 'todos#destroy_selected', as: :destroy_selected
  get 'profile', to: 'users#show'
  get 'users/:id/edit', to: 'users#edit', as: :edit_profile
  put 'users/:id', to: 'users#update', as: :update_profile
  namespace :api  do
    namespace :v1 do
      resources :users
    end
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  mount_uploader :todo_attachment, ProfileImageUploader
  validates :name, :date, :categories, :user, presence: true
  validates_format_of :date, with: /\d{4}\-\d{2}\-\d{2}/, message: 'Date must be in the following format: yyyy-mm-dd'
  serialize :categories, Array
  validates_format_of :reminder_date, with: /\d{4}\-\d{2}\-\d{2}/, message: 'Reminder date must be in the following format: yyyy-mm-dd', if: :reminder
  CATEGORIES = { home: 0, work: 2, vacation: 3, urgent: 4, normal: 5, medical: 6, school: 7, college: 8 }

  validate :validate_categories, :date_not_in_past
  validate :reminder_date_before_due_date, if: :reminder

  scope :completed, -> { where(is_done: true) }
  scope :pending, -> { where('date > ? and is_done = ?', Date.today, false) }
  scope :between_dates, ->(from_date, to_date) { where('date between ? and ?', from_date, to_date) }



  def validate_categories
    if (invalid_categories = (categories - CATEGORIES.keys.map(&:to_s)))
      invalid_categories.each do |category|
        errors.add(:categories, category + " is not a valid category")
      end
    end
  end

  def date_not_in_past
    errors.add(:date, 'Due date can not be in the past') if date.present? && date.to_date < Date.today
  end

  def reminder_date_before_due_date
    if reminder_date.present? && date.present?
      if (reminder_date.to_date > date.to_date) || (reminder_date.to_date < Date.today)
        errors.add(:reminder_date, 'Reminder date should be before the due date and can not be in the past')
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos, dependent: :destroy
  mount_uploader :profile_image, ProfileImageUploader
  enum gender: { male: 0, female: 1, other: 2 }
  validates :email, presence: true, uniqueness: true
  validates :first_name, :last_name, :gender, :address, :profile_image, presence: true
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  def index
    @users = User.all
    render json: @users, include: [:todos]
  end

  def destroy
    begin
	    @user = User.find(params[:id])
	    if @user.destroy
	      render json: { status: 'Success', message: 'User deleted' }
	    else
	      render json: { status: 'Fail', message: 'Error while deleting user' }
	    end
    rescue ActiveRecord::RecordNotFound 
      render json: { error: "Record not found for user" }, status: :not_found
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || profile_path
  end

  def record_not_found
    render 'record_not_found'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name gender address profile_image])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include TodosHelper
  before_action :authenticate_user!

  def index
    @todos = current_user.todos
  end

  def search
    @todos = TodosHelper.search(params, current_user)
  end

  def new
    @todo = current_user.todos.build
  end

  def create
    @todo = current_user.todos.new(todo_params)
    if @todo.save
      flash[:notice] = 'Todo created successfully.'
      redirect_to todos_path
    else
      flash[:alert] = 'Something went wrong.'
      render :new
    end
  end

  def show
    @todo = current_user.todos.find(params[:id])
  end

  def edit
    @todo = current_user.todos.find(params[:id])
  end

  def update
    @todo = current_user.todos.find(params[:id])
    if @todo.update todo_params
      flash[:notice] = 'Todo updated successfully.'
      redirect_to todo_path(@todo)
    else
      flash[:alert] = 'Something went wrong.'
      render :edit
    end
  end

  def destroy
    if current_user.todos.find(params[:id]).destroy
      flash[:notice] = 'Todo Deleted successfully.'
    else
      flash[:alert] = 'Something went wrong.'
    end
    redirect_to todos_path
  end

  def destroy_selected
    todos = current_user.todos.where(id: params[:todo_ids])
    if todos.present?
      todos.destroy_all
      flash[:notice] = 'Selected todos deleted succesfully.'
    else
      flash[:alert] = 'Something went wrong.'
    end
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :date, :is_done, :reminder,
                                 :reminder_date, :is_public, :user_id, :todo_attachment, categories: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:user][:id])
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :email, :password,
                                 :password_confirmation, :gender, :address, :profile_image)
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts = {}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/todos_helper.rb
module TodosHelper
  def self.search(params, current_user)
  	todos = current_user.todos

  	if params[:from_date].present? && !params[:to_date].present?
  		todos = todos.where("date >=?", params[:from_date])
  	elsif !params[:from_date].present? && params[:to_date].present?
  		todos = todos.where("date <=?", params[:to_date])
  	elsif params[:from_date].present? && params[:to_date].present?
  		todos = todos.between_dates(params[:from_date], params[:to_date])
  	end
  	if params[:categories].present?
  		ids = []
     	todos.each {|a| ids << a.id if !(a.categories & params[:categories]).empty? }
     	todos = todos.where(id: ids.uniq)
  	end
  	if params[:completed].present?
  		todos = todos.completed
  	end
  	if params[:pending].present?
  		todos = todos.pending
  	end
  	return todos
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<div class="navbar float-left">
<% if user_signed_in? %>
  <%= link_to 'Edit profile', edit_profile_path(current_user.id), class: 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
<% end %>
</div>
<div class="main">
<%= yield %>
</div>

<script type="text/javascript">
	$(function() {
	  setTimeout(function() {
	    $('.alert').fadeOut('fast');
	  }, 5000)
	})
</script>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_group_for f, :name, label: false  do %>
  <div>
    <%= f.label :name, "Title:" %>
  </div>
  <div>
    <%= f.text_field :name, class: "form-control" %>
  </div>
<% end %>
<div class="form-group">
  <div>
    <%= f.label :categories, "Categories:" %>
  </div>
  <div>
    <%= form_group_for f, :categories, label: false  do %>
    <% Todo::CATEGORIES.each do |category, key| %>
      <%= check_box_tag "todo[categories][]", category,f.object.categories.include?(category.to_s), { multiple: true } %>

    <label><%=category%></label><br>
    <% end%>
    <% end %>
    </br>
  </div>
</div>
<%= form_group_for f, :date, label: false  do %>
  <div>
    <%= f.label :date, "Date:" %>
  </div>
   <div class="input-group date">
    
    <%= f.text_field :date, value: f.object.date, class: "form-control", autocomplete: 'off' %><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    
  </div>
<% end %>
<% unless f.object.new_record? %>
<div class="form-group">
  <div>
    <%= f.label :is_done, "Mark Done:" %>
  </div>
  <div>
    <%= f.check_box :is_done %>
  </div>
</div>
<% end %>
<div class="form-check">
  <div>
    <%= f.label :reminder, "Add Reminder:" %>
  </div>
  <div>
    <%= f.check_box :reminder %>
  </div>
</div>
<div id="reminder_date">
<%= form_group_for f, :reminder_date, label: false do %>
  <div>
    <%= f.label :reminder_date, "Reminder Date:" %>
  </div>
  <div class="input-group date">
    
    <%= f.text_field :reminder_date, value: f.object.reminder_date, class: "form-control", autocomplete: 'off' %><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    
  </div>
<% end %>
</div>
<div class="form-check">
    <div>
      <%= f.label :is_public, "Is Public" %>
    </div>
    <div>
      <%= f.label :is_public, "Yes", value: "true"  %>
      <%= f.radio_button :is_public, true %>
      <%= f.label :is_public, "No", value: "false" %>
      <%= f.radio_button :is_public, false, checked: true %>
    </div>
</div>
<div class="form-group">
  <div>
    <%= f.label :todo_attachment, "Todo Attachment" %>
  </div>
  <div>
    <%= f.file_field :todo_attachment, class: "form-control-file" %>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $("#todo_date").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#todo_reminder_date").datepicker({
      format: 'yyyy-mm-dd'
    });
    $("#reminder_date").hide();
    checkReminder();
  })
  
  $("#todo_reminder").on("change",function(){
    checkReminder();
  })
  
  function checkReminder() {
    if ($("#todo_reminder").is(":checked")) {
      $("#reminder_date").show();
    }else{
      $("#reminder_date").hide();
      $("#todo_reminder_date").val("");
    } 
  }

  function validateForm(e) {
    if ($("#todo_reminder").is(":checked")) {
      if ($("#todo_reminder_date").val() == "") {
        alert("Please add reminder date")
        return false;
      }else if (new Date($("#todo_reminder_date").val()) > new Date($("#todo_date").val())) {
        alert("Reminder date can not be greater than the due date");
        return false;
      }
    }else if (new Date($("#todo_date").val()) < new Date()) {
      alert("Please select date greater that today's date")
      return false;
    }else{
      return true;
    }
  }
</script>

app/views/todos/_todos_list.html.erb
<thead>
	<th></th>
	<th>Item<i class="fa fa-fw fa-sort"></</th>
	<th>Categories<i class="fa fa-fw fa-sort"></</th>
	<th>Due Date<i class="fa fa-fw fa-sort"></</th>
	<th>Reminder Alert<i class="fa fa-fw fa-sort"></</th>
	<th>Completed<i class="fa fa-fw fa-sort"></</th>
	<th colspan="3"></th>
</thead>
<tbody>
	<%if @todos.present?%>
		<% @todos.each do |todo| %>
			<% if todo.reminder_date.present? && todo.reminder_date.between?(Date.today.beginning_of_day, Date.today.end_of_day) %>
					<% reminder_class = "reminder_class"%>
			<% else %>
				 <% reminder_class = ""%>
			<% end %>
			<tr class="<%= reminder_class%>" data-name="<%= todo.name %>" data-date="<%= todo.date%>">
				<td><input type="checkbox" name="todo_ids[]" value="<%= todo.id%>"></td>
				<%todo_presenter = TodoPresenter.new(todo)%>
				<td><%=todo.name%></td>
				<td><%=todo_presenter.todo_category%></td>
				<td data-dateformat="YYYY-MM-DD"><%=todo.date%></td>
				<td><%=todo.reminder%></td>
				<td><%=todo.is_done%></td>
				<td><%= link_to "View", todo_path(todo)%></td>
				<td><%= link_to "Edit", edit_todo_path(todo)%></td>
				<td><%= link_to "Delete", todo, method: :delete, data: { confirm: "You sure?" }%></td>
			</tr>
		<% end %>
	<% else %>
		<tr class="text-center"><td colspan=7>No record found.</td></tr>
	<% end %>
</tbody>

app/views/todos/edit.html.erb
<h1>Edit Your Todo</h1>
<%= form_for @todo, html: {onsubmit: "return validateForm(this);", class: "todo_form"} do |f| %>
  <%= render "form", f: f%>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to "Back To Todo List",todos_path, class: "btn btn-info"%>

app/views/todos/index.html.erb
<p><%= link_to "New Todo Item", new_todo_path, class: "btn btn-info" %></p>
<div>
<%= form_tag(search_path, method: :post,remote: true, id: "search_form") do%>
<br>
	<div>
		<label>Filter todo list based on date, categories and status:</label>
	</div>
	<br>
	<div id="date_search" class="form-group">
		<div class='input-group date' id='datepicker-from-date'><label>From date: <%= text_field_tag :from_date,nil, class: "form-control", autocomplete: 'off'%><span class="input-group-addon">
    <span class="glyphicon glyphicon-calendar"></span>
    </span></div> </label>
		<div class='input-group date' id='datepicker-to-date'><label>To date: <%= text_field_tag :to_date,nil, class: "form-control", autocomplete: 'off'%><span class="input-group-addon">
    <span class="glyphicon glyphicon-calendar"></span>
    </span></div></label>
	</div>
	<div>
		<label>Categories: </label>
		<%= select_tag "categories[]", options_for_select(Todo::CATEGORIES.map { |k, v| [k.to_s.titleize, k]}), multiple: "multiple", class: "selectpicker"%>
		<label>Completed</label>
		<%= check_box_tag "completed", true%>
		<label>Pending</label>
		<%= check_box_tag "pending", true%>
	</div>
	<br>
<% end %>
</div><br>
<%= form_tag destroy_selected_path, method: :delete,remote: true do %>
<table class="table table-bordered table-striped sortable" id="todos_table">
	<%= render "todos_list", locals: {todos: @todos}%>
</table>
<%if @todos.present?%>
	<%= submit_tag 'Delete selected', class: "btn btn-primary" %><br><br>
	<%= link_to "Refresh Todo List", todos_path, class: "btn btn-success"%>
<% end %>
<% end %>



<script type="text/javascript">
	$(document).ready(function(){
		$('.selectpicker').multiselect({
			autoClose: true,
			onChange: function(element, checked) {
	      $("#search_form").submit();
      }
		});

		$("#from_date").datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true
    }).on('changeDate', function(e) {
    	if (($("#from_date").val() > $("#to_date").val()) && $("#to_date").val() != "") {
        alert("From date can not be greater that to date");
        $('#from_date').val('')
      }else{
      	$("#search_form").submit();
      }
    });
    $("#to_date").datepicker({
      format: 'yyyy-mm-dd',
      autoclose: true
    }).on('changeDate', function(e) {
    	if (($("#from_date").val() > $("#to_date").val()) && $("#from_date").val() != "") {
        alert("From date can not be greater that to date");
        $('#to_date').val('')
      }else{
      	$("#search_form").submit();
      }
    });

    $("#completed").on("change",function(){
    	$("#search_form").submit();
    })

    $("#pending").on("change",function(){
    	$("#search_form").submit();
    })
		if ($("tr.reminder_class").length > 0) {
 			$.each($("tr.reminder_class"),function(){
				var name = $(this).data("name");
				var date = $(this).data("date");
				setTimeout(function(){ alert("Reminder: Todo item - "+name+" needs to be done. Due date is "+date) }, 2000);
			})
		}
	})
</script>

app/views/todos/new.html.erb
<h1>Create a New Todo</h1>
<%= form_for @todo, html: {onsubmit: "return validateForm(this);", class: "todo_form"} do |f| %>
  <%= render "form", f: f%>
  <%= f.submit "Create", class: "btn btn-primary create-todo" %>
<% end %>
<br>
<%= link_to "Back To Todo List",todos_path, class: "btn btn-info"%>

app/views/todos/search.js.erb
$("#todos_table").html("<%= escape_javascript render(partial: 'todos_list', locals: { todos: @todos }) %>");

app/views/todos/show.html.erb
<h1>Todo Item</h1>
<p><strong>Title:</strong> <%= @todo['name']%></p>
<p><strong>Due Date:</strong> <%= @todo['date']%></p>
<% presenter = TodoPresenter.new(@todo)%>
<p><strong>Categories:</strong> <%= presenter.todo_category%></p>
<p><strong>Reminder Alert:</strong> <%= @todo['reminder']%></p>
<p><strong>Reminder Date:</strong> <%= @todo['reminder_date']%></p>
<p><strong>Mark Done:</strong> <%= @todo['is_done']%></p>
<p><strong>Todo Attachment:</strong> <%= image_tag @todo.todo_attachment.url, width: "100", height: "100" if @todo.todo_attachment.present? %> </p>

<%= link_to "Edit Todo", edit_todo_path(@todo), class: "btn btn-warning"%>

<%= link_to "Back To Todo List", todos_path, class: "btn btn-info"%>

app/views/users/edit.html.erb
<%= link_to "View Todo List",todos_path, :class => "btn btn-info"%>
<h2>Edit Profile</h2>

<%= form_for(@user,  url: update_profile_path(@user.id), html: { method: :put }) do |f| %>
  <%= f.hidden_field :id, value: @user.id%>
  <%= form_group_for f, :first_name, label: false  do %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class: "form-control" %>
  <% end %>

  <%= form_group_for f, :last_name, label: false  do %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class: "form-control" %>
  <% end %>

  <%= form_group_for f, :gender, label: false  do %>
    <%= f.label :gender %>
    <%= f.select :gender, options_for_select(User.genders.map {|k, v| [k.humanize.capitalize, k]}, :selected => @user.gender),{}, {autofocus: true, autocomplete: "gender", class: "form-control"} %>
  <% end %>
  <%= form_group_for f, :address, label: false  do %>
    <%= f.label :address %>
    <%= f.text_area :address, autofocus: true, autocomplete: "address", class: "form-control" %>
  <% end %>

  <%= form_group_for f, :profile_image, label: false  do %>
    <%= f.label :profile_image %>
    <%= image_tag f.object.profile_image.url if f.object.profile_image.present? %>
    <%= f.file_field :profile_image, autofocus: true, autocomplete: "profile_image", class: "form-control-file" %>
  <% end %>


  <div class="actions">
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= link_to "Create Todo",new_todo_path, class: "btn btn-info"%>
<h2>Profile Details:</h2>

<ul style="list-style: none;">
	<li><strong>First Name:</strong> <%= @user.first_name%></li>
	<li><strong>Last Name:</strong> <%= @user.last_name%></li>
	<li><strong>Email:</strong> <%= @user.email%></li>
	<li><strong>Address:</strong> <%= @user.address%></li>
	<li><strong>Gender:</strong> <%= @user.gender%></li>
	<li><strong>Profile Image:</strong> <%= image_tag @user.profile_image.url, width: "100", height: 100%></li>
</ul>

<%= link_to "View Todo List",todos_path, class: "btn btn-success"%>